### Importing Libraries

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.axes as ax

from sklearn import datasets
from sklearn.metrics import mean_squared_error

import warnings
warnings.filterwarnings("ignore")

### Loading Data

In [19]:
from sklearn.datasets import fetch_california_housing
data = fetch_california_housing()

### Data

In [20]:
x = data.data

In [21]:
y = data.target

In [22]:
features = data.feature_names
features

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [24]:
print (x_train.shape, y_train.shape)
print (x_test.shape, y_test.shape)

(16512, 8) (16512,)
(4128, 8) (4128,)


## <font color = "green">K-Fold Cross validation</font>

In [25]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5, shuffle=False)

for train_index, test_index in kfold.split(x):
    print("Train - \n", train_index, "\nTest - \n", test_index)
    print("=======\n")
# kfold.split(x)

Train - 
 [ 4128  4129  4130 ... 20637 20638 20639] 
Test - 
 [   0    1    2 ... 4125 4126 4127]

Train - 
 [    0     1     2 ... 20637 20638 20639] 
Test - 
 [4128 4129 4130 ... 8253 8254 8255]

Train - 
 [    0     1     2 ... 20637 20638 20639] 
Test - 
 [ 8256  8257  8258 ... 12381 12382 12383]

Train - 
 [    0     1     2 ... 20637 20638 20639] 
Test - 
 [12384 12385 12386 ... 16509 16510 16511]

Train - 
 [    0     1     2 ... 16509 16510 16511] 
Test - 
 [16512 16513 16514 ... 20637 20638 20639]



In [ ]:
rf1= RandomForestRegressor()

n_est = [100, 200, 500]

for n_estimator in n_est:       
    error = []
    for train_index, test_index in kfold.split(x):
        
        x_train, x_test = x[train_index], x[test_index]
        y_train, y_test = y[train_index], y[test_index]
    
        rf1 = RandomForestRegressor(n_estimator)

        rf1 = rf1.fit(x_train, y_train)

        prediction = rf1.predict(x_test)
        
        error.append(mean_squared_error(y_test, prediction))
    print("Results for n_estimator: ", n_estimator)
    print(error)
    print("Average Error = ", sum(error)/len(error))

Results for n_estimator:  100
[0.5155091839024172, 0.3482034958620736, 0.3713576249935928, 0.44237418531342276, 0.4626223882242113]
Average Error =  0.4280133756591436
Results for n_estimator:  200
[0.5171896156322112, 0.3436246199400656, 0.37073044243132525, 0.4481797421966189, 0.4650227135870203]
Average Error =  0.4289494267574483


In [ ]:
error