In [9]:
import pandas as pd

# Creating a matrix from a 2D array
matrix_data = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_df = pd.DataFrame(matrix_data)
print(matrix_df)


   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [6]:
matrix_df = pd.DataFrame(matrix_data)
print(matrix_df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [7]:
# 1st element(0,0)
element = matrix_df.iloc[0, 0]
print("Element at position (0, 0):", element)

# row
row = matrix_df.iloc[0]
print("First row:", row)

# column
column = matrix_df.iloc[:, 0]
print("First column:", column)


Element at position (0, 0): 1
First row: 0    1
1    2
2    3
Name: 0, dtype: int64
First column: 0    1
1    4
2    7
Name: 0, dtype: int64


In [10]:
# Transpose
transposed_matrix = matrix_df.T
print("Transposed matrix:")
print(transposed_matrix)

# sum of the matrix
matrix_sum = matrix_df + matrix_df
print("Matrix sum:")
print(matrix_sum)

# multiplication
matrix_product = matrix_df.dot(matrix_df)
print("Matrix product:")
print(matrix_product)


Transposed matrix:
   0  1  2
0  1  4  7
1  2  5  8
2  3  6  9
Matrix sum:
    0   1   2
0   2   4   6
1   8  10  12
2  14  16  18
Matrix product:
     0    1    2
0   30   36   42
1   66   81   96
2  102  126  150


## Numpy

In [11]:
import numpy as np

# Creating a matrix from a 2D array
matrix_data = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix_data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
# 1st element(0,0)
element = matrix_data[0, 0]
print("Element at position (0, 0):", element)

# row
row = matrix_data[0]
print("First row:", row)

# colum
column = matrix_data[:, 0]
print("First column:", column)

Element at position (0, 0): 1
First row: [1 2 3]
First column: [1 4 7]


In [23]:
# Transpose
transposed_matrix = matrix_data.T
print("Transposed matrix:")
print(transposed_matrix)

# Addition
matrix_sum = matrix_data + matrix_data
print("Matrix sum:")
print(matrix_sum)

# Multiplication
matrix_product = np.dot(matrix_data, matrix_data)
print("Matrix product:")
print(matrix_product)

# Matrix inversion
matrix_inverse = np.linalg.inv(matrix_data)
print("Inverse matrix:")
print(matrix_inverse)

# Determinant 
determinant = np.linalg.det(matrix_data)
print("Determinant of the matrix:", determinant)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix_data)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Transposed matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Matrix sum:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix product:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Inverse matrix:
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Determinant of the matrix: -9.51619735392994e-16
Eigenvalues: [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Eigenvectors: [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
